// Slide
export const GET_SLIDE_REQUEST = "GET_SLIDE_REQUEST"
export const GET_SLIDE_SUCCESS = "GET_SLIDE_SUCCESS"
export const GET_SLIDE_FAILURE = "GET_SLIDE_FAILURE"

export const ADD_SLIDE_REQUEST = "ADD_SLIDE_REQUEST"
export const ADD_SLIDE_SUCCESS = "ADD_SLIDE_SUCCESS"
export const ADD_SLIDE_FAILURE = "ADD_SLIDE_FAILURE"

export const EDIT_SLIDE_REQUEST = "EDIT_SLIDE_REQUEST"
export const EDIT_SLIDE_SUCCESS = "EDIT_SLIDE_SUCCESS"
export const EDIT_SLIDE_FAILURE = "EDIT_SLIDE_FAILURE"

export const DELETE_SLIDE_REQUEST = "DELETE_SLIDE_REQUEST"
export const DELETE_SLIDE_SUCCESS = "DELETE_SLIDE_SUCCESS"
export const DELETE_SLIDE_FAILURE = "DELETE_SLIDE_FAILURE"

export const SEARCH_SLIDE_REQUEST = "SEARCH_SLIDE_REQUEST"
export const SEARCH_SLIDE_SUCCESS = "SEARCH_SLIDE_SUCCESS"
export const SEARCH_SLIDE_FAILURE = "SEARCH_SLIDE_FAILURE"

// Benefit
export const GET_BENEFIT_REQUEST = "GET_BENEFIT_REQUEST"
export const GET_BENEFIT_SUCCESS = "GET_BENEFIT_SUCCESS"
export const GET_BENEFIT_FAILURE = "GET_BENEFIT_FAILURE"

export const ADD_BENEFIT_REQUEST = "ADD_BENEFIT_REQUEST"
export const ADD_BENEFIT_SUCCESS = "ADD_BENEFIT_SUCCESS"
export const ADD_BENEFIT_FAILURE = "ADD_BENEFIT_FAILURE"

export const EDIT_BENEFIT_REQUEST = "EDIT_BENEFIT_REQUEST"
export const EDIT_BENEFIT_SUCCESS = "EDIT_BENEFIT_SUCCESS"
export const EDIT_BENEFIT_FAILURE = "EDIT_BENEFIT_FAILURE"

export const DELETE_BENEFIT_REQUEST = "DELETE_BENEFIT_REQUEST"
export const DELETE_BENEFIT_SUCCESS = "DELETE_BENEFIT_SUCCESS"
export const DELETE_BENEFIT_FAILURE = "DELETE_BENEFIT_FAILURE"

export const SEARCH_BENEFIT_REQUEST = "SEARCH_BENEFIT_REQUEST"
export const SEARCH_BENEFIT_SUCCESS = "SEARCH_BENEFIT_SUCCESS"
export const SEARCH_BENEFIT_FAILURE = "SEARCH_BENEFIT_FAILURE"


// Activities
export const GET_ACTIVITY_REQUEST = "GET_ACTIVITY_REQUEST"
export const GET_ACTIVITY_SUCCESS = "GET_ACTIVITY_SUCCESS"
export const GET_ACTIVITY_FAILURE = "GET_ACTIVITY_FAILURE"

export const ADD_ACTIVITY_REQUEST = "ADD_ACTIVITY_REQUEST"
export const ADD_ACTIVITY_SUCCESS = "ADD_ACTIVITY_SUCCESS"
export const ADD_ACTIVITY_FAILURE = "ADD_ACTIVITY_FAILURE"

export const EDIT_ACTIVITY_REQUEST = "EDIT_ACTIVITY_REQUEST"
export const EDIT_ACTIVITY_SUCCESS = "EDIT_ACTIVITY_SUCCESS"
export const EDIT_ACTIVITY_FAILURE = "EDIT_ACTIVITY_FAILURE"

export const DELETE_ACTIVITY_REQUEST = "DELETE_ACTIVITY_REQUEST"
export const DELETE_ACTIVITY_SUCCESS = "DELETE_ACTIVITY_SUCCESS"
export const DELETE_ACTIVITY_FAILURE = "DELETE_ACTIVITY_FAILURE"

export const SEARCH_ACTIVITY_REQUEST = "SEARCH_ACTIVITY_REQUEST"
export const SEARCH_ACTIVITY_SUCCESS = "SEARCH_ACTIVITY_SUCCESS"
export const SEARCH_ACTIVITY_FAILURE = "SEARCH_ACTIVITY_FAILURE"

// Difference
export const GET_DIFFERENCE_REQUEST = "GET_DIFFERENCE_REQUEST"
export const GET_DIFFERENCE_SUCCESS = "GET_DIFFERENCE_SUCCESS"
export const GET_DIFFERENCE_FAILURE = "GET_DIFFERENCE_FAILURE"

export const ADD_DIFFERENCE_REQUEST = "ADD_DIFFERENCE_REQUEST"
export const ADD_DIFFERENCE_SUCCESS = "ADD_DIFFERENCE_SUCCESS"
export const ADD_DIFFERENCE_FAILURE = "ADD_DIFFERENCE_FAILURE"

export const EDIT_DIFFERENCE_REQUEST = "EDIT_DIFFERENCE_REQUEST"
export const EDIT_DIFFERENCE_SUCCESS = "EDIT_DIFFERENCE_SUCCESS"
export const EDIT_DIFFERENCE_FAILURE = "EDIT_DIFFERENCE_FAILURE"

export const DELETE_DIFFERENCE_REQUEST = "DELETE_DIFFERENCE_REQUEST"
export const DELETE_DIFFERENCE_SUCCESS = "DELETE_DIFFERENCE_SUCCESS"
export const DELETE_DIFFERENCE_FAILURE = "DELETE_DIFFERENCE_FAILURE"

export const SEARCH_DIFFERENCE_REQUEST = "SEARCH_DIFFERENCE_REQUEST"
export const SEARCH_DIFFERENCE_SUCCESS = "SEARCH_DIFFERENCE_SUCCESS"
export const SEARCH_DIFFERENCE_FAILURE = "SEARCH_DIFFERENCE_FAILURE"

// Feedback
export const GET_FEEDBACK_REQUEST = "GET_FEEDBACK_REQUEST"
export const GET_FEEDBACK_SUCCESS = "GET_FEEDBACK_SUCCESS"
export const GET_FEEDBACK_FAILURE = "GET_FEEDBACK_FAILURE"

export const ADD_FEEDBACK_REQUEST = "ADD_FEEDBACK_REQUEST"
export const ADD_FEEDBACK_SUCCESS = "ADD_FEEDBACK_SUCCESS"
export const ADD_FEEDBACK_FAILURE = "ADD_FEEDBACK_FAILURE"

export const EDIT_FEEDBACK_REQUEST = "EDIT_FEEDBACK_REQUEST"
export const EDIT_FEEDBACK_SUCCESS = "EDIT_FEEDBACK_SUCCESS"
export const EDIT_FEEDBACK_FAILURE = "EDIT_FEEDBACK_FAILURE"

export const DELETE_FEEDBACK_REQUEST = "DELETE_FEEDBACK_REQUEST"
export const DELETE_FEEDBACK_SUCCESS = "DELETE_FEEDBACK_SUCCESS"
export const DELETE_FEEDBACK_FAILURE = "DELETE_FEEDBACK_FAILURE"

export const SEARCH_FEEDBACK_REQUEST = "SEARCH_FEEDBACK_REQUEST"
export const SEARCH_FEEDBACK_SUCCESS = "SEARCH_FEEDBACK_SUCCESS"
export const SEARCH_FEEDBACK_FAILURE = "SEARCH_FEEDBACK_FAILURE"

// Popular
export const GET_POPULAR_REQUEST = "GET_POPULAR_REQUEST"
export const GET_POPULAR_SUCCESS = "GET_POPULAR_SUCCESS"
export const GET_POPULAR_FAILURE = "GET_POPULAR_FAILURE"

export const ADD_POPULAR_REQUEST = "ADD_POPULAR_REQUEST"
export const ADD_POPULAR_SUCCESS = "ADD_POPULAR_SUCCESS"
export const ADD_POPULAR_FAILURE = "ADD_POPULAR_FAILURE"

export const EDIT_POPULAR_REQUEST = "EDIT_POPULAR_REQUEST"
export const EDIT_POPULAR_SUCCESS = "EDIT_POPULAR_SUCCESS"
export const EDIT_POPULAR_FAILURE = "EDIT_POPULAR_FAILURE"

export const DELETE_POPULAR_REQUEST = "DELETE_POPULAR_REQUEST"
export const DELETE_POPULAR_SUCCESS = "DELETE_POPULAR_SUCCESS"
export const DELETE_POPULAR_FAILURE = "DELETE_POPULAR_FAILURE"

export const SEARCH_POPULAR_REQUEST = "SEARCH_POPULAR_REQUEST"
export const SEARCH_POPULAR_SUCCESS = "SEARCH_POPULAR_SUCCESS"
export const SEARCH_POPULAR_FAILURE = "SEARCH_POPULAR_FAILURE"

// Register
export const GET_REGISTER_REQUEST = "GET_REGISTER_REQUEST"
export const GET_REGISTER_SUCCESS = "GET_REGISTER_SUCCESS"
export const GET_REGISTER_FAILURE = "GET_REGISTER_FAILURE"

export const ADD_REGISTER_REQUEST = "ADD_REGISTER_REQUEST"
export const ADD_REGISTER_SUCCESS = "ADD_REGISTER_SUCCESS"
export const ADD_REGISTER_FAILURE = "ADD_REGISTER_FAILURE"

export const EDIT_REGISTER_REQUEST = "EDIT_REGISTER_REQUEST"
export const EDIT_REGISTER_SUCCESS = "EDIT_REGISTER_SUCCESS"
export const EDIT_REGISTER_FAILURE = "EDIT_REGISTER_FAILURE"

export const DELETE_REGISTER_REQUEST = "DELETE_REGISTER_REQUEST"
export const DELETE_REGISTER_SUCCESS = "DELETE_REGISTER_SUCCESS"
export const DELETE_REGISTER_FAILURE = "DELETE_REGISTER_FAILURE"

export const SEARCH_REGISTER_REQUEST = "SEARCH_REGISTER_REQUEST"
export const SEARCH_REGISTER_SUCCESS = "SEARCH_REGISTER_SUCCESS"
export const SEARCH_REGISTER_FAILURE = "SEARCH_REGISTER_FAILURE"